"""ChatBI / NL2SQL domain contracts and datasource metadata foundation."""

from .agent import (
    CHATBI_ANALYSIS_PROMPT_VERSION,
    ChatBIAgentLimits,
    ChatBIAgentService,
    ChatBIAnalysisPayload,
    ChatBIResult,
    ChatBITraceEvent,
    ChatBIUsageSummary,
    build_chatbi_analysis_messages,
)
from .credentials import (
    CredentialResolver,
    EnvironmentCredentialResolver,
    ResolvedDatabaseCredentials,
    SecretReferenceResolver,
)
from .discovery import (
    SchemaDiscoveryAdapter,
    SchemaDiscoveryService,
    create_postgres_schema_discovery_service,
)
from .errors import ChatBIError, ChatBIErrorCategory
from .execution import (
    ExecutionAdapter,
    ExecutionAuditRecorder,
    PostgresExecutionAdapter,
    SQLExecutionAuditRecord,
    SQLExecutionOutcome,
    SQLExecutionService,
    build_safe_search_path_statement,
    redact_sql_literals,
)
from .nl2sql import (
    NL2SQL_REASONING_MODE,
    NL2SQLService,
    RegisteredDataSourceProvider,
    SchemaDiscoveryProvider,
    build_nl2sql_messages,
    build_nl2sql_repair_messages,
)
from .nl2sql_models import (
    NL2SQL_MAX_TOKENS,
    RESULT_CONTRACT_VERSION,
    NL2SQLInput,
    NL2SQLResult,
    ResultContract,
    SQLCandidate,
    SQLGenerationPayload,
)
from .policy import QueryPolicy, SQLDialect, default_query_policy
from .result_contract import (
    AggregateFunction,
    OutputColumnKind,
    ResultGrain,
    ResultOrderByTerm,
    ResultOutputColumn,
    SortDirection,
    build_result_contract_prompt_example,
    validate_result_contract,
    validate_sql_result_contract,
)
from .schema_models import (
    SchemaColumn,
    SchemaContextBudgetError,
    SchemaDiscoveryResult,
    SchemaForeignKey,
    SchemaObjectKind,
    SchemaRelation,
    SchemaSnapshot,
    SchemaUniqueConstraint,
    SemanticSchemaContext,
    build_semantic_schema_context,
    normalize_postgres_type,
    render_structural_schema_context,
)
from .schemas import (
    ColumnMetadata,
    DataSource,
    DataSourceCreate,
    DataSourcePublic,
    DataSourceUpdate,
    QueryAuditRecord,
    QueryExecutionRequest,
    QueryExecutionResult,
    QueryLifecycleState,
    QueryTruncationReason,
    validate_connection_ref,
)
from .sql_validation import policy_fingerprint

__all__ = [
    "CHATBI_ANALYSIS_PROMPT_VERSION",
    "NL2SQL_MAX_TOKENS",
    "NL2SQL_REASONING_MODE",
    "RESULT_CONTRACT_VERSION",
    "AggregateFunction",
    "ChatBIAgentLimits",
    "ChatBIAgentService",
    "ChatBIAnalysisPayload",
    "ChatBIError",
    "ChatBIErrorCategory",
    "ChatBIResult",
    "ChatBITraceEvent",
    "ChatBIUsageSummary",
    "ColumnMetadata",
    "CredentialResolver",
    "DataSource",
    "DataSourceCreate",
    "DataSourcePublic",
    "DataSourceUpdate",
    "EnvironmentCredentialResolver",
    "ExecutionAdapter",
    "ExecutionAuditRecorder",
    "NL2SQLInput",
    "NL2SQLResult",
    "NL2SQLService",
    "OutputColumnKind",
    "PostgresExecutionAdapter",
    "QueryAuditRecord",
    "QueryExecutionRequest",
    "QueryExecutionResult",
    "QueryLifecycleState",
    "QueryPolicy",
    "QueryTruncationReason",
    "RegisteredDataSourceProvider",
    "ResolvedDatabaseCredentials",
    "ResultContract",
    "ResultGrain",
    "ResultOrderByTerm",
    "ResultOutputColumn",
    "SQLCandidate",
    "SQLDialect",
    "SQLExecutionAuditRecord",
    "SQLExecutionOutcome",
    "SQLExecutionService",
    "SQLGenerationPayload",
    "SchemaColumn",
    "SchemaContextBudgetError",
    "SchemaDiscoveryAdapter",
    "SchemaDiscoveryProvider",
    "SchemaDiscoveryResult",
    "SchemaDiscoveryService",
    "SchemaForeignKey",
    "SchemaObjectKind",
    "SchemaRelation",
    "SchemaSnapshot",
    "SchemaUniqueConstraint",
    "SecretReferenceResolver",
    "SemanticSchemaContext",
    "SortDirection",
    "build_chatbi_analysis_messages",
    "build_nl2sql_messages",
    "build_nl2sql_repair_messages",
    "build_result_contract_prompt_example",
    "build_safe_search_path_statement",
    "build_semantic_schema_context",
    "create_postgres_schema_discovery_service",
    "default_query_policy",
    "normalize_postgres_type",
    "policy_fingerprint",
    "redact_sql_literals",
    "render_structural_schema_context",
    "validate_connection_ref",
    "validate_result_contract",
    "validate_sql_result_contract",
]
